version: '3'

services:
    api:
        image: node:12-alpine
        command: sh -c "npm run monitor"
        restart: always
        working_dir: /app
        ports:
            - '1337:1337'
        volumes:
            - .:/app
        depends_on:
            - redis           
    redis:
        image: redis:alpine
        restart: always
        ports:
          - 6379:6379
        volumes:
          - redis-data:/data
        command: [ "redis-server", "--appendonly", "yes"]
volumes:
  redis-data: